(function(){
const S=.01,C={m:[1,.929,0,1],s:[1,0,.329,1],g:[0,1,.784,1],p:[.231,.51,.965,1],w:[1,1,1,1],b:[0,0,0,1]};
const V="attribute vec3 p;uniform mat4 P,V,M;void main(){gl_Position=P*V*M*vec4(p,1.0);}";
const F="precision mediump float;uniform vec4 C;uniform float G;void main(){gl_FragColor=vec4(min(C.rgb*(1.0+G),vec3(1.0)),C.a);}";
const sc=(gl,t,s)=>{let x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x};
const pr=gl=>{let p=gl.createProgram();gl.attachShader(p,sc(gl,gl.VERTEX_SHADER,V));gl.attachShader(p,sc(gl,gl.FRAGMENT_SHADER,F));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p};
const me=(gl,v,m)=>{let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STATIC_DRAW);return{b,n:v.length/3,m}};
const mat=(x,y,z,a,b,c)=>[a,0,0,0,0,b,0,0,0,0,c,0,x,y,z,1];
function oct(gl){return me(gl,[0,1,0,-1,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,1,0,1,0,0,0,-1,-1,0,0,0,1,0,0,-1,0,0,0,0,-1,1,0,0,0,0,-1,-1,0,0,0,0,-1,0,0,1,0,0,-1,0,0,1,0,0,0,1,0,0,0,-1,0,0,1,0,0,0,-1,0,0,0,1,0,0,0,-1],gl.TRIANGLES)}
function sph(gl){let v=[],la=6,lo=10,q=(p,a)=>[Math.cos(p)*Math.cos(a),Math.sin(p),Math.cos(p)*Math.sin(a)];for(let i=0;i<la;i++)for(let j=0;j<lo;j++){let p= Math.PI*i/la-Math.PI/2,r=Math.PI*(i+1)/la-Math.PI/2,a=2*Math.PI*j/lo,b=2*Math.PI*(j+1)/lo,A=q(p,a),B=q(r,a),D=q(p,b),E=q(r,b);v.push(...A,...B,...E,...A,...E,...D)}return me(gl,v,gl.TRIANGLES)}
class R{
constructor(canvas,w){this.c=canvas;this.w=w;this.x=null;this.s=null;this.r=null;this.l=null;this.f=null;this.line=new Float32Array(6)}
init(){if(this.x)return 1;try{let g=this.c.getContext("webgl",{alpha:false,antialias:true,xrCompatible:true});if(!g)throw Error("WebGL is unavailable");this.x=g;this.s=pr(g);this.a=g.getAttribLocation(this.s,"p");this.P=g.getUniformLocation(this.s,"P");this.V=g.getUniformLocation(this.s,"V");this.M=g.getUniformLocation(this.s,"M");this.C=g.getUniformLocation(this.s,"C");this.G=g.getUniformLocation(this.s,"G");this.o=oct(g);this.q=sph(g);this.lb=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.lb);g.bufferData(g.ARRAY_BUFFER,24,g.DYNAMIC_DRAW);g.enable(g.DEPTH_TEST);return 1}catch(e){this.f=String(e.message||e);return 0}}
async start(){if(this.r)return 1;if(!this.init())throw Error(this.f||"WebGL initialization failed");if(!navigator.xr)throw Error("WebXR is unavailable");if(!await navigator.xr.isSessionSupported("immersive-vr"))throw Error("Immersive VR is not supported on this device");this.r=await navigator.xr.requestSession("immersive-vr",{optionalFeatures:["local-floor","hand-tracking"]});await this.x.makeXRCompatible();this.l=new XRWebGLLayer(this.r,this.x);this.r.updateRenderState({baseLayer:this.l});try{this.ref=await this.r.requestReferenceSpace("local-floor")}catch(e){this.ref=await this.r.requestReferenceSpace("local")}this.r.addEventListener("end",()=>this.stop());this.t=0;this.r.requestAnimationFrame((t,f)=>this.frame(t,f));return 1}
stop(){this.r=null;this.ref=null;this.l=null}
draw(v,m,pos,scale,col,glow){let g=this.x;g.bindBuffer(g.ARRAY_BUFFER,m.b);g.vertexAttribPointer(this.a,3,g.FLOAT,false,0,0);g.enableVertexAttribArray(this.a);g.uniformMatrix4fv(this.P,false,v.projectionMatrix);g.uniformMatrix4fv(this.V,false,v.viewMatrix);g.uniformMatrix4fv(this.M,false,mat(pos[0],pos[1],pos[2],scale[0],scale[1],scale[2]));g.uniform4fv(this.C,col);g.uniform1f(this.G,glow||0);g.drawArrays(m.m,0,m.n)}
line(v,a,b,col,glow){let g=this.x;this.line.set([...a,...b]);g.bindBuffer(g.ARRAY_BUFFER,this.lb);g.bufferSubData(g.ARRAY_BUFFER,0,this.line);this.draw(v,{b:this.lb,n:2,m:g.LINES},[0,0,0],[1,1,1],col,glow)}
wp(e){let p=this.w.player;return[(e.x-p.x)*S,(e.y-p.y)*S,(e.z-p.z)*S]}
ent(v,e){let p=this.wp(e);if(e.type==="metaball"){let s=e.radius*S;this.draw(v,this.q,p,[s,s,s],C.m,.05);if(e.pickup&&e.pickup.storedXp>0)this.draw(v,this.q,[p[0],p[1],p[2]+s*.45],[s*.3,s*.3,s*.3],C.b,0)}else if(e.type==="glitch"){let s=e.radius*S;this.draw(v,this.q,p,[s,s,s],C.g,.02)}else{let n=Math.min(32,Math.max(3,this.w.spikePointCount(e))),s=e.radius*S;for(let i=0;i<n;i++){let a=(e.direction||0)+Math.PI*2*i/n,b=(e.direction||0)+Math.PI*2*(i+1)/n;this.line(v,[p[0]+Math.cos(a)*s,p[1]+Math.sin(a)*s,p[2]],[p[0]+Math.cos(b)*s,p[1]+Math.sin(b)*s,p[2]],C.s,0)}}}
eulerFromQuaternion(q){if(!q)return{pitch:0,yaw:0,roll:0};const sinp=2*(q.w*q.x+q.y*q.z),cosp=1-2*(q.x*q.x+q.y*q.y),siny=2*(q.w*q.y-q.z*q.x),cosy=1-2*(q.y*q.y+q.z*q.z),sinr=2*(q.w*q.z+q.x*q.y),cosr=1-2*(q.z*q.z+q.x*q.x);return{pitch:Math.atan2(sinp,cosp),yaw:Math.abs(siny)>=1?(Math.PI/2)*Math.sign(siny):Math.asin(siny),roll:Math.atan2(sinr,cosr)}}
input(f,v){let p=this.w.player,tx=0,ty=0,tz=0,L=null,R=null;for(let i of this.r.inputSources){if(!i.gripSpace)continue;let z=f.getPose(i.gripSpace,this.ref);if(!z)continue;let q=z.transform.position,h={x:q.x,y:q.y,z:q.z};if(i.handedness==="left")L=h;if(i.handedness==="right")R=h;if(i.handedness==="left"||i.handedness==="right"){let a=i.gamepad&&i.gamepad.axes||[],x=a[0]||0,y=a[1]||0;if(i.handedness==="left"){tx+=x;ty-=y}else{tz+=x;ty-=y}}}let n=Math.hypot(tx,ty,tz);if(n>1){tx/=n;ty/=n;tz/=n}let W=h=>h?{x:p.x+h.x/S,y:p.y+h.y/S,z:p.z+h.z/S,active:true}:{x:p.x,y:p.y,z:p.z,active:false},gaze=false;if(L&&v&&v.views&&v.views.length){let t=v.views[0].transform,o=t.orientation,fx=2*(o.x*o.z+o.w*o.y),fy=2*(o.y*o.z-o.w*o.x),fz=1-2*(o.x*o.x+o.y*o.y),dx=L.x-t.position.x,dy=L.y-t.position.y,dz=L.z-t.position.z,d=Math.hypot(dx,dy,dz);if(d)gaze=(fx*dx+fy*dy+fz*dz)/d>.82}this.w.setPlayerInput({thrust:{x:tx,y:ty,z:tz},head:this.eulerFromQuaternion(v&&v.views&&v.views.length?v.views[0].transform.orientation:null),leftHand:W(L),rightHand:W(R),gazeAtLeftHand:gaze})}
drawXp(v,pose){if(!pose)return;let p=pose.transform.position,n=Math.min(32,Math.max(0,this.w.player.xp));for(let i=0;i<n;i++){let a=i*Math.PI*2/Math.max(1,n),q=[p.x+Math.cos(a)*.075,p.y+Math.sin(a)*.075,p.z-.035];this.draw(v,this.q,q,[.008,.008,.008],C.w,1)}}
frame(t,f){if(!this.r)return;let d=this.t?Math.max(0,(t-this.t)/1000):0;this.t=t;let v=f.getViewerPose(this.ref);if(!v){this.r.requestAnimationFrame((a,b)=>this.frame(a,b));return}this.input(f,v);this.w.step(d);let g=this.x;g.bindFramebuffer(g.FRAMEBUFFER,this.l.framebuffer);for(let view of v.views){let q=this.l.getViewport(view);g.viewport(q.x,q.y,q.width,q.height);g.clearColor(0,0,0,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);if(this.w.player.captured){let c=this.wp(this.w.player.trap.center);for(let p of this.w.player.trap.points)this.line(view,this.wp(p),c,C.w,1)}else{for(let e of this.w.metaballs)this.ent(view,e);for(let e of this.w.spikes)this.ent(view,e);for(let e of this.w.glitches)this.ent(view,e);this.draw(view,this.o,[view.transform.position.x,view.transform.position.y,view.transform.position.z],[.18,.18,.18],C.p,.04);for(let i of this.r.inputSources){if(!i.gripSpace)continue;let p=f.getPose(i.gripSpace,this.ref);if(p){let q=p.transform.position;this.draw(view,this.o,[q.x,q.y,q.z],[.055,.055,.055],i.handedness==="left"?C.g:C.p,.08);if(i.handedness==="left")this.drawXp(view,p)}}}}}this.r.requestAnimationFrame((a,b)=>this.frame(a,b))}
}
window.VRRenderer=R;
})();